import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const SHARED_FILE_SPECS = [
  {
    source: ['tooling', 'shared', 'dev.mjs'],
    destination: ['scripts', 'dev.mjs'],
  },
  {
    source: ['tooling', 'shared', 'version.mjs'],
    destination: ['scripts', 'version.mjs'],
  },
];

const GENERATED_FILE_SPECS = [
  {
    destination: ['.github', 'workflows', 'ci.yml'],
    render: renderCiWorkflow,
  },
  {
    destination: ['.github', 'workflows', 'release.yml'],
    render: renderReleaseWorkflow,
  },
];

const LEGACY_FILE_SPECS = [['scripts', 'dev.config.mjs']];

function assert(condition, message) {
  if (!condition) {
    throw new Error(message);
  }
}

function isStringArray(value) {
  return (
    Array.isArray(value) &&
    value.length > 0 &&
    value.every((item) => typeof item === 'string' && item.length > 0)
  );
}

function assertFileMappings(value, targetName, key) {
  assert(Array.isArray(value), `${targetName}: ${key} must be an array`);
  for (const [index, item] of value.entries()) {
    assert(
      item &&
        typeof item === 'object' &&
        typeof item.from === 'string' &&
        typeof item.to === 'string',
      `${targetName}: ${key}[${index}] must contain "from" and "to" string values`,
    );
  }
}

function formatInlineList(values) {
  return `[${values.map((value) => `'${value.replaceAll("'", "''")}'`).join(', ')}]`;
}

function formatMultilineList(values, indent = '            ') {
  return values.map((value) => `${indent}${value}`).join('\n');
}

export function validateBoilerConfig(config, targetName = 'target') {
  assert(config && typeof config === 'object', `${targetName}: boiler.config.mjs must export an object`);

  assert(config.dev && typeof config.dev === 'object', `${targetName}: missing required "dev" config`);
  assert(
    isStringArray(config.dev.buildCommand),
    `${targetName}: dev.buildCommand must be a non-empty string array`,
  );
  assert(config.dev.deploy && typeof config.dev.deploy === 'object', `${targetName}: missing dev.deploy config`);
  assert(
    ['copy', 'delegate'].includes(config.dev.deploy.mode),
    `${targetName}: dev.deploy.mode must be "copy" or "delegate"`,
  );

  if (config.dev.deploy.mode === 'copy') {
    assertFileMappings(config.dev.deploy.staticFiles ?? [], targetName, 'dev.deploy.staticFiles');
    assertFileMappings(config.dev.deploy.watchFiles ?? [], targetName, 'dev.deploy.watchFiles');
  }

  if (config.dev.deploy.mode === 'delegate') {
    assert(
      typeof config.dev.deploy.envVar === 'string' && config.dev.deploy.envVar.length > 0,
      `${targetName}: dev.deploy.envVar must be set for delegate mode`,
    );
  }

  assert(
    config.release && typeof config.release === 'object',
    `${targetName}: missing required "release" config`,
  );
  assert(
    typeof config.release.pluginName === 'string' && config.release.pluginName.length > 0,
    `${targetName}: release.pluginName must be a non-empty string`,
  );
  assert(
    isStringArray(config.release.copyFiles),
    `${targetName}: release.copyFiles must be a non-empty string array`,
  );
  assert(
    isStringArray(config.release.publishFiles),
    `${targetName}: release.publishFiles must be a non-empty string array`,
  );

  if (config.version?.stageFiles !== undefined) {
    assert(
      Array.isArray(config.version.stageFiles) &&
        config.version.stageFiles.every((item) => typeof item === 'string' && item.length > 0),
      `${targetName}: version.stageFiles must be a string array`,
    );
  }

  if (config.ci?.pushBranches !== undefined) {
    assert(
      isStringArray(config.ci.pushBranches),
      `${targetName}: ci.pushBranches must be a non-empty string array when provided`,
    );
  }

  if (config.ci?.testResultsFile !== undefined) {
    assert(
      typeof config.ci.testResultsFile === 'string' && config.ci.testResultsFile.length > 0,
      `${targetName}: ci.testResultsFile must be a non-empty string when provided`,
    );
  }

  return config;
}

export function renderCiWorkflow(config) {
  const pushBranches = config.ci?.pushBranches ?? ['**'];
  const testResultsFile = config.ci?.testResultsFile;
  const lines = [
    '# Synced from obsidian-boiler-template/tooling/sync/index.mjs. Do not edit this file directly.',
    'name: CI',
    '',
    'on:',
    '  push:',
    `    branches: ${formatInlineList(pushBranches)}`,
    '  pull_request:',
    '    types: [opened, synchronize, reopened]',
    '',
    'env:',
    '  HUSKY: 0',
  ];

  if (testResultsFile) {
    lines.push('', 'permissions:', '  checks: write', '  pull-requests: write');
  }

  lines.push(
    '',
    'jobs:',
    '  build:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - uses: actions/checkout@v4',
    '        with:',
    '          fetch-depth: 1',
    '      - name: Install pnpm',
    '        uses: pnpm/action-setup@v4',
    '      - uses: actions/setup-node@v4',
    '        with:',
    "          node-version: '20'",
    "          cache: 'pnpm'",
    '      - name: Install dependencies',
    '        run: pnpm install --frozen-lockfile',
    '      - name: Build',
    '        run: pnpm run build',
    '      - name: Lint',
    '        run: pnpm run lint',
    '      - name: Test',
    '        run: pnpm run test',
  );

  if (testResultsFile) {
    lines.push(
      '      - name: Publish Test Results',
      '        uses: EnricoMi/publish-unit-test-result-action@v2',
      '        if: always()',
      '        with:',
      `          files: '${testResultsFile}'`,
    );
  }

  return `${lines.join('\n')}\n`;
}

export function renderReleaseWorkflow(config) {
  const copyFiles = config.release.copyFiles.join(' ');
  const publishFiles = formatMultilineList(config.release.publishFiles);

  return [
    '# Synced from obsidian-boiler-template/tooling/sync/index.mjs. Do not edit this file directly.',
    'name: Release plugin',
    '',
    'on:',
    '  push:',
    '    tags:',
    "      - '*'",
    '',
    'permissions:',
    '  contents: write',
    '',
    'env:',
    `  PLUGIN_NAME: ${config.release.pluginName}`,
    '',
    'jobs:',
    '  build:',
    '    runs-on: ubuntu-latest',
    '',
    '    env:',
    '      HUSKY: 0',
    '    steps:',
    '      - uses: actions/checkout@v4',
    '      - uses: actions/setup-node@v4',
    '        with:',
    "          node-version: '20'",
    '      - name: Install pnpm',
    '        uses: pnpm/action-setup@v4',
    '      - name: Build',
    '        run: |',
    '          pnpm install --frozen-lockfile',
    '          pnpm run build',
    '          mkdir ${{ env.PLUGIN_NAME }}',
    `          cp ${copyFiles} \${{ env.PLUGIN_NAME }}`,
    '          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}',
    '      - name: Release',
    '        uses: softprops/action-gh-release@v2',
    '        with:',
    '          files: |',
    publishFiles,
    '',
  ].join('\n');
}

export async function loadBoilerConfig(targetRoot) {
  const configPath = path.join(targetRoot, 'boiler.config.mjs');
  assert(fs.existsSync(configPath), `${targetRoot}: missing boiler.config.mjs`);

  const configUrl = pathToFileURL(configPath);
  configUrl.searchParams.set('t', String(fs.statSync(configPath).mtimeMs));

  const imported = await import(configUrl.href);
  return validateBoilerConfig(imported.default ?? imported, path.basename(targetRoot));
}

function createWriteOperation(filePath, content) {
  if (fs.existsSync(filePath) && fs.readFileSync(filePath, 'utf8') === content) {
    return null;
  }

  return {
    kind: 'write',
    action: fs.existsSync(filePath) ? 'UPDATE' : 'CREATE',
    filePath,
    content,
  };
}

function createDeleteOperation(filePath) {
  if (!fs.existsSync(filePath)) {
    return null;
  }

  return {
    kind: 'delete',
    action: 'DELETE',
    filePath,
  };
}

export async function buildSyncPlan({ templateRoot, targetRoot }) {
  const config = await loadBoilerConfig(targetRoot);
  const operations = [];

  for (const spec of SHARED_FILE_SPECS) {
    const sourcePath = path.join(templateRoot, ...spec.source);
    const targetPath = path.join(targetRoot, ...spec.destination);
    const content = fs.readFileSync(sourcePath, 'utf8');
    const operation = createWriteOperation(targetPath, content);
    if (operation) {
      operations.push(operation);
    }
  }

  for (const spec of GENERATED_FILE_SPECS) {
    const targetPath = path.join(targetRoot, ...spec.destination);
    const content = spec.render(config);
    const operation = createWriteOperation(targetPath, content);
    if (operation) {
      operations.push(operation);
    }
  }

  for (const legacyFile of LEGACY_FILE_SPECS) {
    const operation = createDeleteOperation(path.join(targetRoot, ...legacyFile));
    if (operation) {
      operations.push(operation);
    }
  }

  return {
    targetName: path.basename(targetRoot),
    targetRoot,
    operations,
  };
}

export async function applySyncPlan(plan, { dryRun = false, onLog = () => {} } = {}) {
  if (plan.operations.length === 0) {
    onLog(`UNCHANGED ${plan.targetName}`);
    return { ...plan, changes: 0 };
  }

  for (const operation of plan.operations) {
    onLog(`${operation.action} ${path.relative(plan.targetRoot, operation.filePath)}`);
    if (dryRun) {
      continue;
    }

    if (operation.kind === 'write') {
      fs.mkdirSync(path.dirname(operation.filePath), { recursive: true });
      fs.writeFileSync(operation.filePath, operation.content);
      continue;
    }

    fs.rmSync(operation.filePath, { force: true });
  }

  return { ...plan, changes: plan.operations.length };
}

export function resolveTargetRoot(templateRoot, targetName) {
  const templateName = path.basename(templateRoot);
  if (targetName === '.' || targetName === templateName) {
    return templateRoot;
  }

  return path.join(path.dirname(templateRoot), targetName);
}

export function discoverTargetNames(templateRoot) {
  const targets = [];
  const templateName = path.basename(templateRoot);
  if (fs.existsSync(path.join(templateRoot, 'boiler.config.mjs'))) {
    targets.push(templateName);
  }

  const siblingsRoot = path.dirname(templateRoot);
  for (const entry of fs.readdirSync(siblingsRoot, { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name === templateName) {
      continue;
    }

    const configPath = path.join(siblingsRoot, entry.name, 'boiler.config.mjs');
    if (fs.existsSync(configPath)) {
      targets.push(entry.name);
    }
  }

  return targets.sort((left, right) => left.localeCompare(right));
}

export function parseArgs(argv) {
  const options = {
    dryRun: false,
    targets: null,
    help: false,
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === '--dry-run') {
      options.dryRun = true;
      continue;
    }

    if (arg === '--help' || arg === '-h') {
      options.help = true;
      continue;
    }

    if (arg === '--targets' || arg.startsWith('--targets=')) {
      const value = arg === '--targets' ? argv[++index] : arg.slice('--targets='.length);
      assert(value, '--targets requires a comma-separated value');
      options.targets = value
        .split(',')
        .map((item) => item.trim())
        .filter(Boolean);
      continue;
    }

    throw new Error(`Unknown argument: ${arg}`);
  }

  return options;
}

export async function runCli(
  argv,
  {
    templateRoot,
    stdout = process.stdout,
  } = {},
) {
  const options = parseArgs(argv);
  if (options.help) {
    stdout.write(
      [
        'Usage: node scripts/sync-to-plugins.mjs [--targets repo-a,repo-b] [--dry-run]',
        '',
        'Options:',
        '  --targets   Comma-separated target repo names. Defaults to every sibling repo with boiler.config.mjs.',
        '  --dry-run   Show planned changes without writing files.',
        '  --help      Show this help text.',
        '',
      ].join('\n'),
    );
    return { targetCount: 0, changeCount: 0, dryRun: options.dryRun };
  }

  const targetNames = options.targets ?? discoverTargetNames(templateRoot);
  assert(targetNames.length > 0, `No boiler-configured targets found near ${templateRoot}`);

  let changeCount = 0;
  for (const targetName of targetNames) {
    const targetRoot = resolveTargetRoot(templateRoot, targetName);
    assert(fs.existsSync(targetRoot), `Target repo not found: ${targetName}`);

    stdout.write(`\n== ${targetName} ==\n`);
    const plan = await buildSyncPlan({ templateRoot, targetRoot });
    const result = await applySyncPlan(plan, {
      dryRun: options.dryRun,
      onLog: (line) => stdout.write(`${line}\n`),
    });
    changeCount += result.changes;
  }

  stdout.write(
    `\n${options.dryRun ? 'Dry run complete' : 'Sync complete'}: ${targetNames.length} target(s), ${changeCount} change(s)\n`,
  );

  return {
    targetCount: targetNames.length,
    changeCount,
    dryRun: options.dryRun,
  };
}
