#!/usr/bin/env node
// Synced from obsidian-boiler-template/tooling/shared/release.mjs. Do not edit this file directly.

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';

const RELEASE_LEVELS = new Set(['patch', 'minor', 'major']);

function getPnpmCommand() {
  return process.platform === 'win32' ? 'pnpm.cmd' : 'pnpm';
}

function run(command, args) {
  const result = spawnSync(command, args, { stdio: 'inherit' });
  if (result.error) {
    console.error(`Failed to run ${command}: ${result.error.message}`);
    process.exit(1);
  }
  if ((result.status ?? 0) !== 0) {
    process.exit(result.status ?? 1);
  }
}

function runCapture(command, args) {
  const result = spawnSync(command, args, { encoding: 'utf8' });
  if (result.error) {
    console.error(`Failed to run ${command}: ${result.error.message}`);
    process.exit(1);
  }
  if ((result.status ?? 0) !== 0) {
    process.stderr.write(result.stderr ?? '');
    process.exit(result.status ?? 1);
  }

  return (result.stdout ?? '').trim();
}

const level = process.argv[2];
if (!RELEASE_LEVELS.has(level)) {
  console.error(`Usage: node scripts/release.mjs <patch|minor|major>`);
  process.exit(1);
}

const pnpm = getPnpmCommand();
const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
if (pkg.scripts?.['sync:check']) {
  run(pnpm, ['sync:check']);
}
run(pnpm, ['run', 'ci']);

if (fs.existsSync('manifest.json')) {
  const raw = fs.readFileSync('manifest.json', 'utf8');
  const normalized = `${JSON.stringify(JSON.parse(raw), null, '\t')}\n`;
  if (raw !== normalized) {
    fs.writeFileSync('manifest.json', normalized);
    run('git', ['add', 'manifest.json']);
    run('git', ['commit', '-m', 'chore: normalize manifest.json formatting']);
  }
}

const headBeforeVersion = runCapture('git', ['rev-parse', 'HEAD']);
run(pnpm, ['version', level]);

const headAfterVersion = runCapture('git', ['rev-parse', 'HEAD']);
if (headAfterVersion === headBeforeVersion) {
  const nextPkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
  const tagPrefix = runCapture('npm', ['config', 'get', 'tag-version-prefix', '--location=project']);
  const tagName = `${tagPrefix}${nextPkg.version}`;
  const releasableFiles = ['package.json', 'manifest.json', 'versions.json'].filter((file) => fs.existsSync(file));

  run('git', ['add', ...releasableFiles]);
  run('git', ['commit', '-m', `chore(release): ${nextPkg.version}`]);
  run('git', ['tag', tagName]);
  run('git', ['push']);
  run('git', ['push', '--tags']);
}
